### PR TITLE
Modsurfer removed to build successfully with Nix

### LINKED ISSUE #26: Improve CI Speed with Nix and Cachix
We should use Nix and Cachix (Binary Cache) in the continuous integration to improve speed.

### LINKED ISSUE #30: Use wasmparser instead of modsurfer
Perhaps the Cargo.toml in modsurfer-plugins causes this error.

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/3ld36w5xvzp4522pm81i4rcjhwqmn7r3-dummy-src
source root is dummy-src
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
[naersk] cargo_version (read): 1.73.0
[naersk] cargo_message_format (set): json-diagnostic-rendered-ansi
[naersk] cargo_release: --release
[naersk] cargo_options: 
[naersk] cargo_build_options: $cargo_release -j "$NIX_BUILD_CORES" --message-format=$cargo_message_format
[naersk] cargo_test_options: $cargo_release -j "$NIX_BUILD_CORES"
[naersk] RUST_TEST_THREADS: 10
[naersk] cargo_bins_jq_filter: .
[naersk] cargo_build_output_json (created): /private/tmp/nix-build-rust-workspace-deps-unknown.drv-0/tmp.ZguZzvhrPI
[naersk] RUSTFLAGS: 
[naersk] CARGO_BUILD_RUSTFLAGS: 
[naersk] CARGO_BUILD_RUSTFLAGS (updated):  --remap-path-prefix /nix/store/q3izw985x40d4wcsvymfnfcamp0ck1i3-crates-io-dependencies=/sources --remap-path-prefix /nix/store/x5gcsizqdyljm9kfxf9bbvzdg6z6zwr5-git-dependencies=/sources
@nix { "action": "setPhase", "phase": "buildPhase" }
building
cargo build $cargo_release -j "$NIX_BUILD_CORES" --message-format=$cargo_message_format
[0m[0m[1m[33mwarning[0m[1m:[0m /private/tmp/nix-build-rust-workspace-deps-unknown.drv-0/dummy-src/brack-parser/Cargo.toml: dependency (serde) specified without providing a local path, Git repository, version, or workspace dependency to use. This will be considered an error in future versions
[0m[0m[1m[33mwarning[0m[1m:[0m /private/tmp/nix-build-rust-workspace-deps-unknown.drv-0/dummy-src/brack-parser/Cargo.toml: unused manifest key: dependencies.serde.versopm
[0m[0m[1m[31merror[0m[1m:[0m failed to get `modsurfer-plugins` as a dependency of package `brack-plugin v0.1.0 (/private/tmp/nix-build-rust-workspace-deps-unknown.drv-0/dummy-src/brack-plugin)`

Caused by:
  failed to load source for dependency `modsurfer-plugins`

Caused by:
  Unable to update https://github.com/dylibso/modsurfer#0a915ee4

Caused by:
  failed to update replaced source https://github.com/dylibso/modsurfer#0a915ee4

Caused by:
  failed to parse manifest at `/nix/store/x5gcsizqdyljm9kfxf9bbvzdg6z6zwr5-git-dependencies/modsurfer-proto-0.1.0-0a915ee4978d16b1ed0c199320d10d382bf79200/Cargo.toml`

Caused by:
  error inheriting `protobuf` from workspace root manifest's `workspace.dependencies.protobuf`

Caused by:
  failed to find a workspace root
[naersk] cargo returned with exit code 101, exiting
```

### PR DESCRIPTION
**Pull request by momeemt**
close #26 #29 #30 

We can't build this project with Nix because (maybe) modsurfer, a dependency package to parse wasm binary and get function names, doesn't publish to crate.io.
I removed it and checked to build successfully using the CI workflow.

- It changes the plugin specification so that the brack plugin must provide a `get_metadata` function that returns `Vec<Metadata>`.

### CODE REVIEW

File: brack-plugin/src/plugin.rs [hunk 1]
```diff
@@ -104,59 +55,3 @@ pub fn arg_counter(arg_types: &Vec<Type>) -> (usize, usize) {
...
-                    Json((ast.clone(), ast.id())),
-                ) {
-                    Ok(Json(ast)) => println!("{:?}", ast),
-                    Err(e) => panic!("{:?}", e),
-                }
-            }
-            _ => panic!("No metadata found for ^"),
-        }
-    }
-}
```
Comment (uekann) [inline brack-plugin/src/plugin.rs:162]: I think we need a replacement for the erased test.

Comment (uekann) [inline brack-plugin/src/plugin.rs:162]: I think we need a replacement for the erased test.

Comment (momeemt) [reply brack-plugin/src/plugin.rs:162]: Your claim is valid, but currently we have to prepare plugin that meets new specifications. It means that we have to manually generate wasm binary every time the specifications change, so I would like to write unit tests after I will make automation testing system for plugins.
